"""Epsilon v2 test generator. Real tests from HIR TestSpecs, stdlib only.

tests_for() renders one test file per TestSpec: unittest.TestCase files for
Python, node:test files for JavaScript/TypeScript. Every case in the spec --
including edge, invalid, and integration cases -- becomes an assertion block.
Nothing is invented: a spec with N cases yields exactly N test methods.

Calling convention per case (from TestCase.given):
  tuple/list -> positional args, dict -> keyword args (Python) or a single
  object argument (JS, which has no kwargs), any other value -> one argument.
TestCase.expect is a source literal; the generator validates it with
ast.literal_eval at render time and falls back to embedding it verbatim
(with a comment) when it is not a plain literal. TestCase.raises selects
assertRaises / assert.throws instead of a value comparison.
"""
from __future__ import annotations

import ast
import json
import re

from .hir import TestCase, TestSpec


def _get(obj, key: str, default=None):
    if isinstance(obj, dict):
        return obj.get(key, default)
    return getattr(obj, key, default)


def _slug(text: str, fallback: str) -> str:
    s = re.sub(r'[^0-9a-z]+', '_', (text or '').lower()).strip('_')
    return s or fallback


def _proj_lang(project) -> str:
    lang = (_get(project, 'language', 'python') or 'python').lower()
    if lang == 'js':
        return 'javascript'
    if lang not in ('python', 'javascript', 'typescript'):
        return 'python'
    return lang


def _specs(project) -> list:
    return list(_get(project, 'tests', []) or [])


def _cases(spec) -> list:
    return list(_get(spec, 'cases', []) or [])


def _safe_repr(value):
    try:
        return repr(value)
    except Exception:
        return None


def _call_expr(given):
    """Render the argument list for a TARGET(...) call. None if unrenderable."""
    if given is None:
        return '()'
    if isinstance(given, dict):
        parts = []
        for k in sorted(given.keys(), key=str):
            r = _safe_repr(given[k])
            if r is None:
                return None
            parts.append('%s=%s' % (k, r))
        return '(%s)' % ', '.join(parts)
    if isinstance(given, (list, tuple)):
        parts = []
        for v in given:
            r = _safe_repr(v)
            if r is None:
                return None
            parts.append(r)
        return '(%s)' % ', '.join(parts)
    r = _safe_repr(given)
    if r is None:
        return None
    return '(%s)' % r


def _method_name(i: int, note: str) -> str:
    base = 'test_%02d' % i
    if note:
        base += '_' + _slug(note, 'case')[:24]
    return base


def _one_line_note(note) -> str:
    return ' '.join(str(note or '').split())


def _class_name(spec_name: str, target: str) -> str:
    slug = _slug(spec_name or target, 'generated')
    camel = ''.join(p[:1].upper() + p[1:] for p in slug.split('_'))
    name = 'Test' + (camel or 'Generated')
    if not re.match(r'^[A-Za-z_][A-Za-z0-9_]*$', name):
        return 'TestGenerated'
    return name


def _exc_name(raises) -> str:
    name = str(raises or '').strip()
    if re.match(r'^[A-Za-z_][A-Za-z0-9_.]*$', name):
        return name
    return ''


def _python_file(spec_name: str, target: str, cases: list, setup: str) -> str:
    L: list[str] = []
    L.append('"""Generated by epsilon testgen from TestSpec %r."""' % spec_name)
    L.append('import importlib')
    L.append('import unittest')
    L.append('')
    L.append('TARGET_PATH = %r' % target)
    L.append('def _resolve(dotted):')
    L.append('    mod, sep, attr = dotted.rpartition(".")')
    L.append('    if sep:')
    L.append('        try:')
    L.append('            m = importlib.import_module(mod)')
    L.append('        except ImportError:')
    L.append('            return importlib.import_module(dotted)')
    L.append('        obj = m')
    L.append('        for part in attr.split("."):')
    L.append('            obj = getattr(obj, part)')
    L.append('        return obj')
    L.append('    return importlib.import_module(dotted)')
    L.append('')
    L.append('TARGET = _resolve(TARGET_PATH)')
    L.append('')
    if setup and str(setup).strip():
        for line in str(setup).splitlines():
            L.append(line.rstrip())
        L.append('')
    L.append('class %s(unittest.TestCase):' % _class_name(spec_name, target))
    if not cases:
        L.append('    pass  # spec holds no cases; add TestCase nodes to cover it')
    for i, case in enumerate(cases):
        given = _get(case, 'given', None)
        expect = _get(case, 'expect', '')
        raises = _get(case, 'raises', None)
        note = _one_line_note(_get(case, 'note', ''))
        L.append('    def %s(self):' % _method_name(i, note))
        if note:
            L.append('        # %s' % note)
        args = _call_expr(given)
        if args is None:
            L.append('        self.skipTest("unrepresentable given value")')
            continue
        if raises:
            exc = _exc_name(raises)
            if not exc:
                exc = 'Exception  # original raises=%r not an identifier' % (raises,)
            L.append('        with self.assertRaises(%s):' % exc)
            L.append('            TARGET%s' % args)
            continue
        try:
            ast.literal_eval(expect)
            literal_ok = True
        except Exception:
            literal_ok = False
        if not literal_ok:
            L.append('        # non-literal expect from spec; compared verbatim')
        L.append('        actual = TARGET%s' % args)
        L.append('        expected = %s' % expect)
        L.append('        self.assertEqual(actual, expected)')
    L.append('')
    L.append("if __name__ == '__main__':")
    L.append('    unittest.main()')
    return '\n'.join(L) + '\n'


def _js_value(value):
    if isinstance(value, tuple):
        value = list(value)
    if isinstance(value, set):
        value = sorted(value, key=repr)
    try:
        return json.dumps(value, sort_keys=True)
    except (TypeError, ValueError):
        return None


def _js_args(given):
    if given is None:
        return '()'
    if isinstance(given, dict):
        v = _js_value(given)
        return None if v is None else '(%s)' % v
    if isinstance(given, (list, tuple)):
        parts = []
        for item in given:
            v = _js_value(item)
            if v is None:
                return None
            parts.append(v)
        return '(%s)' % ', '.join(parts)
    v = _js_value(given)
    return None if v is None else '(%s)' % v


def _js_expect_block(expect) -> list[str]:
    """Assertion lines over an already-bound `actual` value."""
    try:
        py_value = ast.literal_eval(expect)
    except Exception:
        literal_ok = False
    else:
        literal_ok = True
    if literal_ok:
        js_lit = _js_value(py_value)
        if js_lit is None:
            literal_ok = False
    if not literal_ok:
        return ['// non-literal expect from spec; compared as an expression',
                'assert.strictEqual(actual, (%s));' % expect]
    return ['assert.strictEqual(actual, %s);' % js_lit]
    L.append('    assert.strictEqual(%s, %s);' % (actual_call, js_lit))
    return L


def _js_file(spec_name: str, target: str, cases: list, setup: str,
             lang: str) -> str:
    L: list[str] = []
    L.append('// Generated by epsilon testgen from TestSpec %r.' % spec_name)
    if lang == 'typescript':
        L.append('// Run with a TypeScript-aware runner (tsc/ts-node).')
    L.append("const { test } = require('node:test');")
    L.append("const assert = require('node:assert/strict');")
    L.append('')
    L.append('const TARGET_PATH = %s;' % json.dumps(target))
    L.append('const _parts = TARGET_PATH.split(".");')
    L.append('const _attr = _parts.length > 1 ? _parts.pop() : null;')
    if lang == 'typescript':
        L.append("const _mod = require('../' + _parts.join('/'));")
    else:
        L.append("const _mod = require('../' + _parts.join('/') + '.js');")
    L.append('const TARGET = _attr ? _mod[_attr] : _mod;')
    L.append('')
    if setup and str(setup).strip():
        for line in str(setup).splitlines():
            L.append(line.rstrip())
        L.append('')
    if not cases:
        L.append('// spec holds no cases; add TestCase nodes to cover it')
    for i, case in enumerate(cases):
        given = _get(case, 'given', None)
        expect = _get(case, 'expect', '')
        raises = _get(case, 'raises', None)
        note = _one_line_note(_get(case, 'note', ''))
        title = 'case %d' % i + (': ' + note if note else '')
        title = title.replace('\\', '\\\\').replace("'", "\\'")
        L.append("test('%s', () => {" % title)
        args = _js_args(given)
        if args is None:
            L.append('  // unrepresentable given value; manual review needed')
            L.append('});')
            continue
        if raises:
            exc = _exc_name(raises) or 'Error'
            L.append('  assert.throws(() => { TARGET%s; }, /%s/);'
                     % (args, re.escape(exc)))
            L.append('});')
            continue
        L.append('  const actual = TARGET%s;' % args)
        for line in _js_expect_block(expect):
            L.append('  ' + line)
        L.append('});')
    return '\n'.join(L) + '\n'


def tests_for(project) -> dict:
    """Render one real test file per TestSpec. Returns {path: content}.

    Path convention: tests/test_<slug>.py for Python,
    tests/<slug>.test.js / tests/<slug>.test.ts for JavaScript/TypeScript,
    where <slug> derives from the spec name (or target). Specs with an empty
    target are skipped: without a target there is nothing to resolve.
    """
    lang = _proj_lang(project)
    out: dict[str, str] = {}
    used: set[str] = set()
    for i, spec in enumerate(_specs(project)):
        name = _get(spec, 'name', '') or ''
        target = (_get(spec, 'target', '') or '').strip()
        if not target:
            continue
        slug = _slug(name or target, 'spec_%d' % i)
        if lang == 'python':
            path = 'tests/test_%s.py' % slug
        elif lang == 'typescript':
            path = 'tests/%s.test.ts' % slug
        else:
            path = 'tests/%s.test.js' % slug
        n = 2
        while path in used:
            if lang == 'python':
                path = 'tests/test_%s_%d.py' % (slug, n)
            elif lang == 'typescript':
                path = 'tests/%s_%d.test.ts' % (slug, n)
            else:
                path = 'tests/%s_%d.test.js' % (slug, n)
            n += 1
        used.add(path)
        cases = _cases(spec)
        setup = _get(spec, 'setup', '') or ''
        if lang == 'python':
            out[path] = _python_file(name or target, target, cases, setup)
        else:
            out[path] = _js_file(name or target, target, cases, setup, lang)
    return out


def regression_test(target, given, expect, style='value'):
    """Build a one-case TestSpec from a discovered failure. None if unusable.

    style selects the case shape: 'value' (default) treats expect as a Python
    value and stores its repr() as the expected literal; 'literal' stores an
    expect string verbatim as the expected literal; 'raises' treats expect as
    an exception name for an assertRaises-style case. Unknown styles, empty
    targets, and non-literal-representable values yield None.
    """
    if not isinstance(target, str) or not target.strip():
        return None
    target = target.strip()
    norm = style.lower() if isinstance(style, str) else ''
    name = 'regression_' + _slug(target, 'case')
    if norm == 'raises':
        if isinstance(expect, str) and _exc_name(expect):
            exc = _exc_name(expect)
        elif isinstance(expect, type) and issubclass(expect, BaseException):
            exc = expect.__name__
        elif isinstance(expect, BaseException):
            exc = type(expect).__name__
        else:
            return None
        case = TestCase(given=given, expect='',
                        raises=exc, note='regression: %s raised %s' % (target, exc))
        return TestSpec(name=name, target=target, cases=[case], setup='')
    if norm in ('literal', 'source', 'expect-literal'):
        if not isinstance(expect, str):
            return None
        case = TestCase(given=given, expect=expect,
                        note='regression: %s' % target)
        return TestSpec(name=name, target=target, cases=[case], setup='')
    if norm in ('', 'value'):
        try:
            literal = repr(expect)
        except Exception:
            return None
        try:
            ast.literal_eval(literal)
        except Exception:
            return None
        case = TestCase(given=given, expect=literal,
                        note='regression: %s' % target)
        return TestSpec(name=name, target=target, cases=[case], setup='')
    return None
